[versions]
jna = "5.14.0"
junit = "5.10.3"
vanniktechMavenPublish = "0.30.0"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[plugins]
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
